translations = {
    "ru": {
        "welcome_message": "Добро пожаловать в сервис!",
        "profile_button": "👤 Профиль",
        "remove_account_button": "🔧 Снести аккаунт",
        "buy_subscription_button": "💰 Купить подписку",
        "info_button": "ℹ️ Информация",
        "change_language_button": "🌐 Сменить язык",
        "user_info": "Информация о пользователе",
        "id": "ID",
        "name": "Имя",
        "username": "Юзернейм",
        "no_username": "Не указан",
        "reg_date": "Дата регистрации",
        "not_available": "Не доступна",
        "subscription": "Подписка",
        "no_subscription": "Отсутствует",
        "expires": "Истекает",
        "need_subscription": "Нужна активная подписка для этой функции!",
        "enter_target": "Введите юзернейм или ссылку на канал",
        "select_subscription": "Выберите тариф подписки",
        "selected": "Вы выбрали",
        "confirm_purchase": "Подтвердите покупку",
        "select_valid_plan": "Выберите тариф из списка",
        "confirm_button": "✅ Подтвердить",
        "cancel_button": "🚫 Отмена",
        "action_canceled": "Действие отменено",
        "confirm_or_cancel": "Подтвердите или отмените заказ",
        "invoice_created": "Счет создан",
        "pay_here": "Оплатите по ссылке",
        "check_payment": "Проверьте оплату",
        "invoice_error": "Ошибка создания счета",
        "order_error": "Ошибка обработки заказа",
        "order_accepted": "Заказ принят!",
        "check_payment_button": "✅ Проверить оплату",
        "check_or_cancel": "Проверьте оплату или отмените",
        "payment_confirmed": "Оплата подтверждена",
        "subscription_activated": "Подписка активирована",
        "payment_pending": "Оплата не подтверждена",
        "payment_check_error": "Ошибка проверки оплаты",
        "target_confirmation": "Подтвердите удаление",
        "confirm_order": "Подтвердите заказ",
        "service_info": "Информация о сервисе",
        "service_name": "Снос аккаунтов",
        "how_it_works": "Как это работает",
        "buy_plan": "Купите тариф",
        "enter_target_account": "Укажите аккаунт",
        "send_complaints": "Отправим жалобы",
        "warning": "Внимание: возможны ограничения",
        "no_guarantee": "Блокировка не гарантируется",
        "support": "Свяжитесь с поддержкой",
        "select_language": "Выберите язык",
        "invalid_input": "Выберите действие"
    },
    "en": {
        "welcome_message": "Welcome to the service!",
        "profile_button": "👤 Profile",
        "remove_account_button": "🔧 Remove Account",
        "buy_subscription_button": "💰 Buy Subscription",
        "info_button": "ℹ️ Info",
        "change_language_button": "🌐 Change Language",
        "user_info": "User Information",
        "id": "ID",
        "name": "Name",
        "username": "Username",
        "no_username": "Not specified",
        "reg_date": "Registration Date",
        "not_available": "Not available",
        "subscription": "Subscription",
        "no_subscription": "None",
        "expires": "Expires",
        "need_subscription": "Active subscription required!",
        "enter_target": "Enter username or channel link",
        "select_subscription": "Select subscription plan",
        "selected": "You selected",
        "confirm_purchase": "Confirm purchase",
        "select_valid_plan": "Select a valid plan",
        "confirm_button": "✅ Confirm",
        "cancel_button": "🚫 Cancel",
        "action_canceled": "Action canceled",
        "confirm_or_cancel": "Confirm or cancel order",
        "invoice_created": "Invoice created",
        "pay_here": "Pay here",
        "check_payment": "Check payment",
        "invoice_error": "Invoice creation error",
        "order_error": "Order processing error",
        "order_accepted": "Order accepted!",
        "check_payment_button": "✅ Check Payment",
        "check_or_cancel": "Check payment or cancel",
        "payment_confirmed": "Payment confirmed",
        "subscription_activated": "Subscription activated",
        "payment_pending": "Payment pending",
        "payment_check_error": "Payment check error",
        "target_confirmation": "Confirm removal",
        "confirm_order": "Confirm order",
        "service_info": "Service Information",
        "service_name": "Account Removal",
        "how_it_works": "How it works",
        "buy_plan": "Buy a plan",
        "enter_target_account": "Enter target account",
        "send_complaints": "Send complaints",
        "warning": "Warning: possible restrictions",
        "no_guarantee": "Blocking not guaranteed",
        "support": "Contact support",
        "select_language": "Select language",
        "invalid_input": "Select an action"
    }
}